version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: bull-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
